# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos Ventures SL

# Generated by Django 1.9.2 on 2016-09-14 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiga_contrib_slack', '0003_auto_20150923_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackhook',
            name='notify_epic_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slackhook',
            name='notify_epic_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slackhook',
            name='notify_epic_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slackhook',
            name='notify_relateduserstory_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slackhook',
            name='notify_relateduserstory_delete',
            field=models.BooleanField(default=True),
        ),
    ]
